version: '3'
services:
  auth:
    build: ./auth_service
    container_name: auth_app
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      - auth_db
      - auth_redis
    env_file: ./docker_env/auth.env

  auth_db:
    image: postgres:15
    container_name: auth_db
    env_file: ./docker_env/auth_db.env
    networks:
      - app_network
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  auth_redis:
    image: redis:alpine
    container_name: auth_redis_server
    networks:
      - app_network

  auth_proxy:
    build: ./waf_proxy_service
    container_name: auth_proxy_server
    networks:
      - app_network
    ports:
      - "8005:8005"
    env_file: ./docker_env/auth.env
    restart: always
    depends_on:
      - auth
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:8005/healthz"]

  game:
    build: ./game_service
    container_name: game
    env_file: ./docker_env/game.env
    ports:
      - "8001:8001"
    networks:
      - app_network
    depends_on:
      - game_redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]

  game_redis:
    image: redis:alpine
    container_name: game_redis_server
    networks:
      - app_network

  game_proxy:
    build: ./waf_proxy_service
    container_name: game_proxy_server
    networks:
      - app_network
    ports:
      - "8004:8004"
    env_file: ./docker_env/game.env
    restart: always
    depends_on:
      - game
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:8004/healthz"]

  tournament:
    build: ./tournament_service
    container_name: tournament
    ports:
      - "8002:8002"
    env_file: ./docker_env/tournament.env
    networks:
      - app_network
    depends_on:
      - tournament_db
      - tournament_redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]

  tournament_db:
    image: postgres:15
    container_name: tournament_db
    env_file: ./docker_env/tournament_db.env
    networks:
      - app_network
    volumes:
      - tournament_db_data:/var/lib/postgresql/data

  tournament_redis:
    image: redis:alpine
    container_name: tournament_redis
    networks:
      - app_network
  
  tournament_proxy:
    build: ./waf_proxy_service
    container_name: tournament_proxy_server
    networks:
      - app_network
    ports:
      - "8006:8006"
    env_file: ./docker_env/tournament.env
    restart: always
    depends_on:
      - tournament
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:8006/healthz"]

  user:
    build: ./user_service
    container_name: user_app
    ports:
      - "9000:9000"
    networks:
      - app_network
    depends_on:
      - user_db
    env_file: ./docker_env/user.env

  user_db:
    image: postgres:15
    container_name: user_db
    env_file: ./docker_env/user_db.env
    networks:
      - app_network
    volumes:
      - user_db_data:/var/lib/postgresql/data
  
  friends_activity_app:
    build: ./friends_activity_service
    container_name: friends_activity_app
    ports:
      - "10000:10000"
    networks:
      - app_network

  friends:
    build: ./friends_service
    container_name: friends
    env_file: ./docker_env/friends.env
    ports:
      - "7500:7500"
    networks:
      - app_network
    depends_on:
      - friends_db

  friends_db:
    image: postgres:15
    container_name: friends_db
    env_file: ./docker_env/friends_db.env
    networks:
      - app_network
    volumes:
      - friends_db_data:/var/lib/postgresql/data

  friends_proxy:
    build: ./waf_proxy_service
    container_name: friends_proxy_server
    networks:
      - app_network
    ports:
      - "8007:8007"
    env_file: ./docker_env/friends.env
    restart: always
    depends_on:
      - friends
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:8007/healthz"]

  match:
    build: ./match_service
    container_name: match
    ports:
      - "8003:8003"
    env_file: ./docker_env/match.env
    networks:
      - app_network
    depends_on:
      - match_db
      - match_redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]

  match_db:
    image: postgres:15
    container_name: match_db
    env_file: ./docker_env/match_db.env
    networks:
      - app_network
    volumes:
      - match_db_data:/var/lib/postgresql/data

  match_redis:
    image: redis:alpine
    container_name: match_redis
    networks:
      - app_network

  match_proxy:
    build: ./waf_proxy_service
    container_name: match_proxy_server
    networks:
      - app_network
    ports:
      - "8008:8008"
    env_file: ./docker_env/match.env
    restart: always
    depends_on:
      - match
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:8008/healthz"]

  vault:
    build: ./vault_service
    container_name: vault
    ports:
      - 8200:8200
    networks:
      - app_network
    env_file: ./docker_env/vault.env
    volumes:
      - ./certs/client.crt:/vault/certs/client.crt:ro
      - ./certs/client.key:/vault/certs/client.key:ro
      - ./certs/server.crt:/vault/certs/server.crt:ro
      - ./certs/server.key:/vault/certs/server.key:ro
      - ./certs/ca.crt:/vault/certs/ca.crt:ro

  spa_nginx:
    image: nginx:alpine
    container_name: spa_nginx
    ports:
      - "8080:80"
    networks:
      - app_network
    volumes:
      - ./spa:/usr/share/nginx/html:ro
      - ./spa/nginx.conf:/etc/nginx/conf.d/default.conf:ro


networks:
  app_network:
    driver: bridge

volumes:
  auth_db_data:
  tournament_db_data:
  friends_db_data:
  user_db_data:
  match_db_data:
