version: '3'
services:
  auth:
    build: ./auth_service
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      - auth_db
      - auth_redis
    environment:
      - DJANGO_DB_NAME=auth_db
      - DJANGO_DB_USER=auth_user
      - DJANGO_DB_PASSWORD=auth_password
      - DJANGO_DB_HOST=auth_db
      - DJANGO_DB_PORT=5432
      - REDIS_HOST=auth_redis
      - REDIS_PORT=6379

  auth_db:
    image: postgres:15
    container_name: auth_db
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    networks:
      - app_network
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  auth_redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  auth_db_data:
