version: '3'
services:
  auth:
    build: ./auth_service
    container_name: auth_app
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      - auth_db
      - auth_redis
    env_file: ./docker_env/auth.env

  auth_db:
    image: postgres:15
    container_name: auth_db
    env_file: ./docker_env/auth_db.env
    networks:
      - app_network
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  auth_redis:
    image: redis:alpine
    container_name: auth_redis_server
    networks:
      - app_network

  game:
    build: ./game_service
    container_name: game
    env_file: ./docker_env/game.env
    tty: true
    ports:
      - "8001:8001"
    networks:
      - app_network
    depends_on:
      - game_redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://game:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  game_redis:
    image: redis:alpine
    container_name: game_redis_server
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  auth_db_data:
