groups:
  - name: example-alert
    rules:
      - alert: InstanceDown
        expr: up == 0 # PromQL : サーバーの死活状況に関するクエリ
        for: 30s # Duration : exprsがこの時間続いたらアラートを送信
        labels:
          severity: critical # アラートの重要度
        annotations: # Alert Txt : 事象発生時のテキスト
          firing_text: "Instance {{ $labels.instance }} down"
          resolved_text: "Instance {{ $labels.instance }} up"
      - alert: NginxRequestRateHigh
        expr: rate(nginx_http_requests_total[30s]) > 2 # 継続的に1秒に2リクエスト以上
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "NGINX に大量のアクセス ({{ $labels.instance }})"
          description: "リクエストが急増しています。1秒あたり {{ $value | humanize }} 件"
