global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spa-nginx-exporter'
    static_configs:
      - targets: ['spa_nginx_exporter:9113']
