# Generated by Django 4.2.16 on 2024-11-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='mode',
            field=models.CharField(default='Quick', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner_user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchparticipant',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='owner_user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(default='BeforeStarting', max_length=20),
        ),
    ]
