# Generated by Django 4.2.16 on 2024-11-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_mode_alter_match_winner_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='parent_match_id',
            field=models.IntegerField(null=True),
        ),
    ]
