openapi: 3.0.3

info: 
  title: Auth API
  description: |
    AuthサービスのAPIを提供。このAPIは、ユーザー認証管理に関連する操作をサポート。
  version: 1.0.0

servers:
  - url: https://auth.transcendence.com

paths:
  /auth/me/email:
    put:
      summary: "ユーザのemailを更新"
      description: "認証済みユーザのemailを更新"
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
              required:
                - email
      responses:
        "200":
          description: "Email updated successfully."
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Email updated successfully."
        "400":
          description: "Validation error or invalid email format."
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid email format."
        "401":
          $ref: '#/components/responses/UnauthorizedResponse'
        "409":
          description: "The email address is already registered."
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "This email address is already in use."
  /auth/me/password:
    put:
      summary: "ユーザのpasswordを更新"
      description: "認証済みユーザのpasswordを更新。現在のpasswordも認証に必要。"
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                current_password:
                  type: string
                new_password:
                  type: string
              required:
                - current_password
                - new_password
      responses:
        "200":
          description: "Password updated successfully."
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Password updated successfully."
        "400":
          description: "Validation error or invalid request."
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Current password is incorrect."
        "401":
          $ref: '#/components/responses/UnauthorizedResponse'
  /auth/otp/signup:
    post:
      summary: "新規ユーザーのサインアップ"
      description: "新規ユーザーを仮登録し、認証用のOTPを生成"
      tags:
        - auth
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - username
                - email
                - password
      responses:
        "200":
          description: "OTPが正常に生成"
          headers:
            Set-Cookie:
              description: "OTP認証用に、ユーザー名をCookieに設定"
              schema:
                type: string
                example: "username=johndoe; HttpOnly; Secure; Path=/; Max-Age=300"
          content:
            # qrコードは軽量なのでjsonにした
            application/json:
              schema:
                type: object
                properties:
                  qr_code:
                    type: string
                    description: "OTP用のQRコードを表すBase64エンコード文字列。"
                    example: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUg..."
        "400":
          description: "Invalid input data."
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "エラー詳細"
                    example: "Invalid email format."
        "409":
          description: "The email address or username is already registered."
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "This email address or username is already in use."
  /auth/otp/login:
    post:
      summary: "既存ユーザーのログイン"
      description: "ユーザーを認証し、OTPを生成"
      tags:
        - auth
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        "200":
          description: "ログイン成功、OTPプロセスが開始"
          headers:
            Set-Cookie:
              description: "OTP認証用のユーザー名をCookieに設定"
              schema:
                type: string
                example: "username=johndoe; HttpOnly; Secure; Path=/; Max-Age=300"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "OTPプロセスに関する情報メッセージ"
                    example: "Use the OTP generated by your authentication app to complete the login process."
        "401":
          description: "Invalid username or password."
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "無効なユーザー名またはパスワードを示すエラーメッセージ。"
  /auth/otp/signup/verify:
    post:
      summary: "サインアップ時のOTP検証"
      description: "サインアッププロセス中に送信されたOTPを検証"
      tags:
        - auth
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                otp:
                  type: string
                  description: "ユーザーに送信されたOTP"
              required:
                - username
                - otp
      responses:
        "200":
          description: "OTPが正常に検証され、ユーザをDBに登録"
          headers:
            Set-Cookie:
              description: "usernameクッキーを削除"
              schema:
                type: string
                example: "username=; HttpOnly; Secure; Path=/; Max-Age=0"
          content:
            application/json:
              schema:
                type: object
                properties:
                  access:
                    type: string
                    description: "accessトークン"
                  refresh:
                    type: string
                    description: "refreshトークン"
        "400":
          description: "Invalid OTP or username."
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "無効なOTPまたはユーザー名に関するエラーメッセージ"
        "401":
          description: "User authentication failed."
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "認証失敗に関するエラーメッセージ"
  /auth/otp/login/verify:
    post:
      summary: "ログイン時のOTP検証"
      description: "OTPを検証"
      tags:
        - auth
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                otp:
                  type: string
              required:
                - username
                - otp
      responses:
        "200":
          description: "OTPが正常に検証され、ログインが完了"
          headers:
            Set-Cookie:
              description: "usernameクッキーを削除"
              schema:
                type: string
                example: "username=; HttpOnly; Secure; Path=/; Max-Age=0"
          content:
            application/json:
              schema:
                type: object
                properties:
                  access:
                    type: string
                    description: "アクセストークン"
                  refresh:
                    type: string
                    description: "リフレッシュトークン"
        "400":
          description: "Invalid OTP or username."
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "無効なOTPまたはユーザー名に関するエラーメッセージ"
        "401":
          description: "User authentication failed."
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "認証失敗に関するエラーメッセージ"
  /auth/token/refresh:
    post:
      summary: "accessトークンの更新"
      description: "有効なrefreshトークンを使用して新しいaccessトークンを生成。accessトークン認証はなし"
      tags:
        - auth
      # accessトークンを更新するので、認証しない
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh:
                  type: string
              required:
                - refresh
      responses:
        "200":
          description: "New access token generated."
          content:
            application/json:
              schema:
                type: object
                properties:
                  access:
                    type: string
                    description: "The new access token."
        "400":
          description: "Missing refresh token."
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "エラー詳細"
                    example: "Refresh token is missing."
        "401":
          description: "Invalid or expired refresh token."
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "リフレッシュトークンが無効または期限切れであることを示すエラーメッセージ"
                    example: "Refresh token is missing or invalid."

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UnauthorizedError:
      type: object
      properties:
        error:
          type: string
          description: "認証エラーの詳細"
          example: "JWT is invalid or expired."

  responses:
    UnauthorizedResponse:
      description: "Unauthorized - Missing or invalid JWT."
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UnauthorizedError'
