openapi: 3.0.3

info: 
  title: Friends Activity API
  description: |
    friends activityサービスのAPIを提供
    このAPIは、ユーザのフレンドのオンラインステータスに関連する操作をサポート。
  version: 1.0.0

servers:
  - url: https://friends-activity.transcen.com
  - url: wss://friends-activity.transcen.com

paths:
  /friends/online:
    description: "オンラインのフレンドリストをWebSocketで取得"
    get:
      summary: "オンラインのフレンドリストを取得するWebSocket接続"
      operationId: "getOnlineFriendsWS"
      tags:
        - Friends Activity
      responses:
        '101':
          description: "WebSocket接続の確立"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "WebSocket connection established for online friends list."
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '500':
          description: "サーバーエラー"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "エラーの詳細"
                    example: "Internal server error"

  /health:
    get:
      summary: ヘルスチェック用エンドポイント
      description: dockerコンテナ立ち上げ時のヘルスチェックなど
      operationId: healthCheck
      tags:
        - Friends Activity
      responses:
        '200':
          description: サーバーが正常に稼働中
          content:
            application/json:
              example:
                "status": "healthy"
        '500':
          description: サーバーが正常に稼働していない
          content:
            application/json:
              example:
                "status": "unhealthy"
      security: []

security:
  - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UnauthorizedError:
      type: object
      properties:
        error:
          type: string
          description: "認証エラーの詳細"
          example: "JWT is invalid or expired."

  responses:
    UnauthorizedResponse:
      description: "Unauthorized - Missing or invalid JWT."
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UnauthorizedError'
