openapi: 3.0.3
info:
  title: Matches API
  description: 試合管理機能を実現するAPI
  version: 1.0.0

servers:
  - url: https://matches.42.fr

paths:
  /matches/:
    get:
      summary: 試合を検索
      description: |
        QueryStringを用いて試合を検索する。
        複数条件による検索を許容する。
        user_idに基づいた試合履歴の検索は別のエンドポイントで行う。
      operationId: SearchMatches
      tags:
        - Matches
      parameters:
        - name: match_id
          in: query
          required: false
          schema:
            type: integer
        - name: winner_user_id
          in: query
          required: false
          schema:
            type: integer
        - name: mode
          in: query
          required: false
          schema:
            type: string
            enum: ["QuickPlay", "Tournament"]
        - name: tournament_id
          in: query
          required: false
          schema:
            type: integer
        - name: round
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: 試合が見つかった
          content:
            application/json:
              example: [
                {
                  "match_id": 2,
                  "winner_user_id": 1,
                  "mode": "Tournament",
                  "tournament_id": 1,
                  "parent_match_id": 3,
                  "round": 10,
                  "participants": [
                    {"user_id": 1, "user_name": "ABC"},
                    {"user_id": 2, "user_name": "DEF"}
                  ]
                },
                {
                  "match_id": 3,
                  "winner_user_id": NULL,
                  "mode": "Tournament",
                  "tournament_id": 1,
                  "parent_match_id": NULL,
                  "round": 11,
                  "participants": [
                    {"user_id": 2, "user_name": "DEF"},
                    {"user_id": 3, "user_name": "GHI"}
                  ]
                }
              ]
        '400':
          description: QueryStringがおかしい
          content:
            application/json:
              example:
                "error": "Bad Request"
        "401":
          $ref: '#/components/responses/UnauthorizedResponse'
        '404':
          description: 該当する試合が存在しない
          content:
            application/json:
              example:
                "error": "Match Not Found"
      security:
        - BearerAuth: []

  /matches/create-tournament-match/:
    post:
      summary: トーナメントに紐づいた試合を作成
      description: |
        トーナメント内の試合レコードを作成する。
        トーナメント管理から叩かれる。
      operationId: createTournamentMatch
      tags:
        - Matches
      requestBody:
        description: トーナメント試合作成の基となる情報
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id_list:
                  type: array
                  items:
                    type: integer
                tournament_id:
                  type: integer
                parent_match_id:
                  type: integer
                  nullable: true
                  description: 決勝戦はparent_match_idが存在しないため、NULLを許容する
                round:
                  type: integer
              required:
                - user_id_list
                - tournament_id
                - round
            example:
              "user_id_list": [1, 42]
              "tournament_id": 1
              "parent_match_id": 100
              "round": 1
      responses:
        '200':
          description: トーナメント試合が作成された
          content:
            application/json:
              example:
                "match_id": 101
        '400':
          description: 試合作成の基となる情報に不備がある
          content:
            application/json:
              example:
                "error": "Bad Request"
        "401":
          $ref: '#/components/responses/UnauthorizedResponse'
        '404':
          description: トーナメント管理API以外から叩かれた
          content:
            application/json:
              example:
                "error": "Not Found"
      security:
        - BearerAuth: []

  /matches/ws/enter-room/:
    get:
      summary: QuickPlayマッチングルームに入る
      description: |
        QuickPlayのマッチング待機部屋に入る。
        人数が集まったらGame開始する。
        このWebSocketはGameが開始されたらコネクションを切る。
      operationId: enterMatchRoom
      tags:
        - Matches
      responses:
        '101':
          description: WebSocketへのプロトコルアップデート成功
        '400':
          description: リクエストの情報に誤りがある
          content:
            application/json:
              example:
                "error": "Bad Request"
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
      security:
        - BearerAuth: []

  /matches/ws/enter-room/{match_id}/:
    get:
      summary: トーナメント試合のルームに入る
      description: |
        トーナメントの試合待機部屋に入る。
        試合のレコード自体はトーナメント開始時に作成済み。
        参加者が集まったらGame開始する。
        このWebSocketはGameが開始されたらコネクションを切る。
      operationId: enterTournamentMatchRoom
      tags:
        - Matches
      parameters:
        - name: match_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '101':
          description: WebSocketへのプロトコルアップデート成功
        '400':
          description: リクエストの情報に誤りがある
          content:
            application/json:
              example:
                "error": "Bad Request"
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '404':
          description: |
            存在しないルームに入ろうとした
            or
            許可されていないルームに入ろうとした
          content:
            application/json:
              example:
                "error": "Not Found"
      security:
        - BearerAuth: []

  /matches/finish/:
    post:
      summary: Game終了時に通知を受け取る
      description: |
        Gameが終了した時にGame管理APIから叩かれる。
        試合結果をDBに保存する。
        試合結果をトーナメント管理に通知する。
      operationId: finishMatch
      tags:
        - Matches
      requestBody:
        description: 試合結果情報
        required: true
        content:
          application/json:
            example:
              "match_id": 1
              results: [
                {"user_id": 1, "score": 8},
                {"user_id": 2, "score": 11}
              ]
      responses:
        '204':
          description: 正常にGameが終了
        '400':
          description: リクエストボディと試合テーブルのレコードの整合性が取れない
          content:
            application/json:
              example:
                "error": "Bad Request"
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '404':
          description: Game管理API以外から叩かれた
          content:
            application/json:
              example:
                "error": "Not Found"
      security:
        - BearerAuth: []

  /matches/statistics/{user_id}/:
    get:
      summary: 試合統計情報を取得
      description: 試合に関する統計情報を返す。
      operationId: matchStatistics
      tags:
        - Matches
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 試合勝利回数・試合敗北回数・トーナメント優勝回数
          content:
            application/json:
              example:
                "match_win_count": 20
                "match_lose_count": 8
                "tournament_winner_count": 2
        '400':
          description: user_idがおかしい
          content:
            application/json:
              example:
                "error": "Bad Request"
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
      security:
        - BearerAuth: []

  /matches/history/{user_id}/:
    get:
      summary: 試合履歴リストを取得
      description: 試合履歴をリスト形式で取得する。
      operationId: matchHistoryList
      tags:
        - Matches
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 試合モード・対戦相手・勝敗・スコア・試合日時
          content:
            application/json:
              example: [
                {
                  "mode": "QuickPlay",
                  "win_or_lose": "win",
                  "date": "2024-12-09",
                  "user_score": 11,
                  "opponent_list": [
                    {"name": "User2", "score": 5}
                  ],
                },
                {
                  "mode": "Tournament",
                  "win_or_lose": "lose",
                  "date": "2024-12-01",
                  "user_score": 10,
                  "opponent_list": [
                    {"name": "User3", "score": 12}
                  ],
                }
              ]
        '400':
          description: user_idがおかしい
          content:
            application/json:
              example:
                "error": "Bad Request"
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
      security:
        - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UnauthorizedError:
      type: object
      properties:
        error:
          type: string
          description: "認証エラーの詳細"
          example: "JWT is invalid or expired."

  responses:
    UnauthorizedResponse:
      description: "Unauthorized - Missing or invalid JWT."
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UnauthorizedError'
