# Generated by Django 5.1.3 on 2024-11-22 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memo',
            old_name='created_detetime',
            new_name='created_datetime',
        ),
    ]
