openapi: 3.0.0
info:
  title: Friend API
  version: 1.0.0
  description: ft_transcendence内のフレンド機能を実装するためのAPI

servers:
  - url: https://friend.42.fr

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []

paths:
  /friends/:
    get:
      summary: ユーザーのフレンド情報を取得
      operationId: getFriends
      responses:
        '200':
          description: ユーザーの全てのフレンドを取得
          content:
            application/json:
              example: [
                {
                  "friend_user_id": 2,
                  "friend_user_name": "ABC",
                  "request_sent_at": "2024-12-02",
                  "approved_at": "2024-12-02",
                },
                {
                  "from_user_id": 3,
                  "friend_user_name": "DEF",
                  "request_sent_at": "2024-12-03",
                  "approved_at": "2024-12-09",
                }
              ]
  /friends/{user_id}/:
    delete:
      summary: フレンド削除
      operationId: deleteFriend
      parameters:
       - name: user_id
         in: path
         required: true
         schema:
           type: integer
      responses:
        '204':
          description: フレンド削除成功
        '400':
          description: フレンド削除失敗
  /friends/requests/:
    post:
      summary: フレンド申請を送信
      operationId: sendFriendRequest
      requestBody:
        description: フレンド申請先ユーザーのuser_id
        required: true
        content:
          application/json:
            example:
              "receiver_user_id": 456
      responses:
        '200':
          description: フレンド申請先の情報を取得
          content:
            application/json:
              example:
                "user_id": 2
                "user_name": "ABC"
                "request_sent_at": "2024-12-02"
        '400':
          description: Invalid user_id
  /friends/requests/{user_id}/:
    delete:
      summary: フレンド申請拒否
      operationId: deleteFriendRequest
      parameters:
       - name: user_id
         in: path
         required: true
         schema:
           type: integer
      responses:
        '204':
          description: フレンド申請拒否成功
        '400':
          description: フレンド申請拒否失敗
  /friends/requests/approve/:
    post:
      summary: フレンド申請を承認
      operationId: approveFriendRequest
      requestBody:
        description: フレンド申請もとユーザーのuser_id
        required: true
        content:
          application/json:
            example:
              "requester_user_id": 123
      responses:
        '200':
          description: 承認したフレンドの情報を取得
          content:
            application/json:
              example:
                "friend_user_id": 2
                "friend_user_name": "ABC"
                "request_sent_at": "2024-12-02"
                "approved_at": "2024-12-09"
        '400':
          description: Invalid requester_user_id
  /friends/requests/received/:
    get:
      summary: ユーザーにフレンド申請しているユーザーの情報を取得
      operationId: getFrinedReceivedInfo
      responses:
        '200':
          description: ユーザーにフレンド申請しているユーザーの情報を取得
          content:
            application/json:
              example: [
                {
                  "user_id": 2,
                  "friend_user_name": "ABC",
                  "request_sent_at": "2024-12-02",
                },
                {
                  "user_id": 3,
                  "friend_user_name": "DEF",
                  "request_sent_at": "2024-12-03",
                }
              ]
  /friends/requests/sent/:
    get:
      summary: ユーザーがフレンド申請しているユーザーの情報を取得
      operationId: getFrinedSentInfo
      responses:
        '200':
          description: ユーザーがフレンド申請しているユーザーの情報を取得
          content:
            application/json:
              example: [
                {
                  "user_id": 2,
                  "user_name": "ABC",
                  "request_sent_at": "2024-12-02",
                },
                {
                  "user_id": 3,
                  "user_name": "DEF",
                  "request_sent_at": "2024-12-03",
                }
              ]
