name: Lint and Format Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened
  workflow_dispatch:

jobs:
  lint-and-fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run lint and format check
        run: make check
